trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: Install Node.js

- script: npm install
  displayName: npm install

- script: |
    echo "Creating staticwebapp.config.json"

    mkdir -p public

    cat <<EOF > public/staticwebapp.config.json
    {
      "navigationFallback": {
        "rewrite": "/index.html",
        "exclude": ["/assets/*", "/*.css", "/*.js", "/*.png", "/*.jpg"]
      }
    }
    EOF

    echo "Generated config:"
    cat public/staticwebapp.config.json

  displayName: Generate staticwebapp.config.json

- script: |
    echo "API URL: $VITE_API_URL"
    echo "APIM KEY: $(VITE_Apim_Subscription_Key)"
  displayName: Debug env variables
  env:
    VITE_API_URL: $(VITE_API_URL)
    VITE_selfhostllm_URL: $(VITE_selfhostllm_URL)
    VITE_Apim_Subscription_Key: $(VITE_Apim_Subscription_Key)

- script: |
    npm run build
  displayName: npm build
  env:
    VITE_API_URL: $(VITE_API_URL)
    VITE_selfhostllm_URL: $(VITE_selfhostllm_URL)
    VITE_APIM_SUBSCRIPTION_KEY: $(VITE_APIM_SUBSCRIPTION_KEY)   

- task: AzureStaticWebApp@0
  displayName: Deploying in Azure static web app
  inputs:
    app_location: /
    output_location: dist
    azure_static_web_apps_api_token: $(deployment token)