# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: Install Node.js

- script: npm install
  displayName: npm install

- script: |
    echo "Creating staticwebapp.config.json"

    mkdir -p public

    cat <<EOF > public/staticwebapp.config.json
    {
      "routes": [
        {
          "route": "/apim/*",
          "rewrite": "${VITE_API_URL}/:splat"
        }
      ],
      "navigationFallback": {
        "rewrite": "/index.html",
        "exclude": [
          "/assets/*",
          "/*.css",
          "/*.js",
          "/*.png",
          "/*.jpg",
          "/apim/*"
        ]
      }
    }
    EOF

    echo "Generated config:"
    cat public/staticwebapp.config.json

  displayName: Generate staticwebapp.config.json
  env:
    VITE_API_URL: $(VITE_API_URL)

- script: |
    echo "API URL: $VITE_API_URL"
    npm run build
  displayName: npm build
  env:
    VITE_API_URL: $(VITE_API_URL)
    VITE_selfhostllm_URL: $(VITE_selfhostllm_URL)

- task: AzureStaticWebApp@0
  inputs:
    app_location: /
    output_location: dist
    azure_static_web_apps_api_token: $(deployment token)